sml.hibernate.dialect=org.hibernate.dialect.MySQLDialect
sml.datasource.jndi=java:comp/env/jdbc/edelivery
sml.jsp.servlet.class=org.apache.jasper.servlet.JspServlet
sml.log.folder=/data/domisml/logs
sml.libraries.folder=/data/domisml/domisml-libs
sml.security.folder=/data/domisml/security
log.configuration.file=/opt/domisml/classes/sml-logback.xml
sml.ws.servicemetadataservices.schema-validation-enabled=true
sml.ws.participantservices.schema-validation-enabled=true
sml.ws.bdmslservices.schema-validation-enabled=true
sml.ws.bdmsladminservices.schema-validation-enabled=true
